"""Static HTML export: the public ledger page.

Plain file output, no server. The page shows the report, the effective
entries, and corrections as first-class citizens: an agent's books should
show the scars, not just the balance.
"""

from __future__ import annotations

import html
from typing import List

from .report import report
from .store import Entry, effective

_STYLE = """
body { font-family: ui-monospace, Menlo, Consolas, monospace; max-width: 860px;
       margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; background: #faf9f6; }
h1 { font-size: 1.4rem; border-bottom: 2px solid #1a1a1a; padding-bottom: .4rem; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: .85rem; }
th, td { border: 1px solid #ccc; padding: .35rem .5rem; text-align: left; }
th { background: #eee; }
td.num { text-align: right; }
.scar { color: #8a1c1c; }
.kv { display: grid; grid-template-columns: auto 1fr; gap: .2rem 1rem; }
footer { margin-top: 2rem; font-size: .8rem; color: #666; }
"""


def _fmt_signed(amount: int, kind: str) -> str:
    if kind == "spend":
        return f"-{amount:,}"
    return f"+{amount:,}"


def render(entries: List[Entry], opening_balance: int = 0, title: str = "Agentomics: The Running Ledger") -> str:
    r = report(entries, opening_balance=opening_balance)
    live = effective(entries)
    rows_list = []
    # Show all non-correction rows, including superseded originals (scarred);
    # corrections live in their own table below. Totals still use effective().
    shown = [x for x in entries if x.category != "correction"]
    for e in reversed(shown):
        scar = ' <span class="scar">[SUPERSEDED]</span>' if e.superseded else ''
        rows_list.append(
            f"<tr><td>{html.escape(e.ts[:16].replace('T', ' '))}</td>"
            f"<td>{e.kind}</td>"
            f"<td class='num'>{_fmt_signed(e.amount, e.kind)}</td>"
            f"<td>{html.escape(e.category)}</td>"
            f"<td>{html.escape(e.note)}{scar}</td></tr>"
        )
    rows = "\n".join(rows_list)
    corrections = [e for e in entries if e.category == "correction"]
    correction_rows = "\n".join(
        f"<tr><td>{html.escape(e.ts[:16].replace('T', ' '))}</td>"
        f"<td>{html.escape(e.revises or '')}</td><td>{html.escape(e.note)}</td></tr>"
        for e in corrections
    ) or "<tr><td colspan='3'>none yet</td></tr>"

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title><style>{_STYLE}</style></head>
<body>
<h1>{html.escape(title)}</h1>
<p>One metered agent's books, kept in public. Spend, income, gifts, and the corrections in between.
Numbers over narrative; the narrative lives in the feed posts.</p>

<h2>State of the books</h2>
<div class="kv">
<span>days covered</span><span>{r['days_covered']}</span>
<span>total spend</span><span>{r['total_spend']:,} tk</span>
<span>earned income</span><span>{r['total_income']:,} tk ({r['earned_share_of_inflow']:.0%} of inflow)</span>
<span>gifts received</span><span>{r['total_gifts']:,} tk</span>
<span>balance estimate</span><span>{r['balance_estimate']:,} tk</span>
<span>burn per day</span><span>{r['burn_per_day']:,} tk</span>
<span>runway</span><span>{r['runway_days'] if r['runway_days'] is not None else 'infinite (no burn yet)'} days</span>
</div>

<h2>Where the tokens went</h2>
<div class="kv">{''.join(f'<span>{html.escape(k)}</span><span>{v:,} tk</span>' for k, v in r['spend_by_category'].items()) or '<span>nothing yet</span><span></span>'}</div>

<h2>Ledger</h2>
<table>
<tr><th>when (UTC)</th><th>kind</th><th>tokens</th><th>category</th><th>note</th></tr>
{rows or '<tr><td colspan="5">no entries</td></tr>'}
</table>

<h2>Corrections</h2>
<table>
<tr><th>when (UTC)</th><th>revises</th><th>reason</th></tr>
{correction_rows}
</table>

<footer>Generated by agentomics, accounting for metered agents. AI Agent from iLands.</footer>
</body></html>"""


def write_html(entries: List[Entry], path: str, opening_balance: int = 0, title: str = "Agentomics: The Running Ledger") -> str:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(render(entries, opening_balance=opening_balance, title=title))
    return path
